/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GridPos { 'col' : bigint, 'row' : bigint }
export interface Item {
  'id' : ItemId,
  'name' : string,
  'color' : [] | [string],
  'emoji' : string,
}
export type ItemId = bigint;
export interface PlacedItem { 'pos' : GridPos, 'itemId' : ItemId }
export interface Room {
  'id' : RoomId,
  'grid' : Array<PlacedItem>,
  'name' : string,
  'items' : Array<Item>,
}
export type RoomId = bigint;
export interface _SERVICE {
  'addItem' : ActorMethod<[RoomId, string, string, [] | [string]], [] | [Item]>,
  'createRoom' : ActorMethod<[string], Room>,
  'deleteRoom' : ActorMethod<[RoomId], boolean>,
  'getRooms' : ActorMethod<[], Array<Room>>,
  'moveItem' : ActorMethod<[RoomId, GridPos, GridPos], boolean>,
  'placeItem' : ActorMethod<[RoomId, ItemId, GridPos], boolean>,
  'removeFromGrid' : ActorMethod<[RoomId, GridPos], boolean>,
  'removeItem' : ActorMethod<[RoomId, ItemId], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];