/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RoomId = IDL.Nat;
export const ItemId = IDL.Nat;
export const Item = IDL.Record({
  'id' : ItemId,
  'name' : IDL.Text,
  'color' : IDL.Opt(IDL.Text),
  'emoji' : IDL.Text,
});
export const GridPos = IDL.Record({ 'col' : IDL.Nat, 'row' : IDL.Nat });
export const PlacedItem = IDL.Record({ 'pos' : GridPos, 'itemId' : ItemId });
export const Room = IDL.Record({
  'id' : RoomId,
  'grid' : IDL.Vec(PlacedItem),
  'name' : IDL.Text,
  'items' : IDL.Vec(Item),
});

export const idlService = IDL.Service({
  'addItem' : IDL.Func(
      [RoomId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Opt(Item)],
      [],
    ),
  'createRoom' : IDL.Func([IDL.Text], [Room], []),
  'deleteRoom' : IDL.Func([RoomId], [IDL.Bool], []),
  'getRooms' : IDL.Func([], [IDL.Vec(Room)], []),
  'moveItem' : IDL.Func([RoomId, GridPos, GridPos], [IDL.Bool], []),
  'placeItem' : IDL.Func([RoomId, ItemId, GridPos], [IDL.Bool], []),
  'removeFromGrid' : IDL.Func([RoomId, GridPos], [IDL.Bool], []),
  'removeItem' : IDL.Func([RoomId, ItemId], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RoomId = IDL.Nat;
  const ItemId = IDL.Nat;
  const Item = IDL.Record({
    'id' : ItemId,
    'name' : IDL.Text,
    'color' : IDL.Opt(IDL.Text),
    'emoji' : IDL.Text,
  });
  const GridPos = IDL.Record({ 'col' : IDL.Nat, 'row' : IDL.Nat });
  const PlacedItem = IDL.Record({ 'pos' : GridPos, 'itemId' : ItemId });
  const Room = IDL.Record({
    'id' : RoomId,
    'grid' : IDL.Vec(PlacedItem),
    'name' : IDL.Text,
    'items' : IDL.Vec(Item),
  });
  
  return IDL.Service({
    'addItem' : IDL.Func(
        [RoomId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Opt(Item)],
        [],
      ),
    'createRoom' : IDL.Func([IDL.Text], [Room], []),
    'deleteRoom' : IDL.Func([RoomId], [IDL.Bool], []),
    'getRooms' : IDL.Func([], [IDL.Vec(Room)], []),
    'moveItem' : IDL.Func([RoomId, GridPos, GridPos], [IDL.Bool], []),
    'placeItem' : IDL.Func([RoomId, ItemId, GridPos], [IDL.Bool], []),
    'removeFromGrid' : IDL.Func([RoomId, GridPos], [IDL.Bool], []),
    'removeItem' : IDL.Func([RoomId, ItemId], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };